# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVibe < Formula
  desc "git-vibe is a git plugin that uses an llm to help with common git tasks"
  homepage "https://github.com/fcjr/git-vibe"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.1/git-vibe_Darwin_x86_64.tar.gz"
      sha256 "70f835b2d10128a45d3ff43c6728e300a9de6fd39c813d377a4c0e36149e8454"

      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.1/git-vibe_Darwin_arm64.tar.gz"
      sha256 "41cc549e23f8b42ca05ee934fe38a8c9023b62a06c797dd894fcb4baad807058"

      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.1/git-vibe_Linux_x86_64.tar.gz"
      sha256 "3f7e6d9527aa6fd0c9dd5f8a70f1ed30dff5944e4bbfc6bd47849d23d5cfcff4"
      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.1/git-vibe_Linux_arm64.tar.gz"
      sha256 "017806afac6ff372917eaec96b8fa73486d19795be6f81fbc5d870ebec1f526e"
      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
  end
end
