# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVibe < Formula
  desc "git-vibe is a git plugin that uses an llm to help with common git tasks"
  homepage "https://github.com/fcjr/git-vibe"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.2/git-vibe_Darwin_x86_64.tar.gz"
      sha256 "1feeabb19501e6e0a2c22ea930f68ab2680665e3971f9bda633a999ee6a559af"

      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.2/git-vibe_Darwin_arm64.tar.gz"
      sha256 "b941510b00f2d8b5ecaaa36856ce3b519cd3757b8ee32f959b129d01721d8f10"

      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.2/git-vibe_Linux_x86_64.tar.gz"
      sha256 "11feb01244072cfdec8421800989b2a7fb707ccf73b003b8c07b843479f44be9"
      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fcjr/git-vibe/releases/download/v0.0.2/git-vibe_Linux_arm64.tar.gz"
      sha256 "38bb0a35dba4aee679e545f3782d6f30a75f6b05fbf6a6d7bd55f9d7a5e85d36"
      def install
        bin.install "git-vibe"
        bash_completion.install "completions/git-vibe.bash" => "git-vibe"
        zsh_completion.install "completions/git-vibe.zsh" => "_git-vibe"
        fish_completion.install "completions/git-vibe.fish"
        man1.install "manpages/git-vibe.1.gz"
      end
    end
  end
end
