# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smock < Formula
  desc "Smock Image Editor"
  homepage "https://www.leftshift.com"
  version "0.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fcjr/smock/releases/download/v0.0.2/smock_0.0.2_macOS_x86_64.tar.gz"
      sha256 "a6862eec6487c3fd56a6863aaf5fef9dc785c5aa4621ed6cc80aa614ed3a09be"
    end
    if Hardware::CPU.arm?
      url "https://github.com/fcjr/smock/releases/download/v0.0.2/smock_0.0.2_macOS_arm64.tar.gz"
      sha256 "7e7dee30614a9a2d88add19664f441c3e4b20fef7d93e34ec295067536706c31"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fcjr/smock/releases/download/v0.0.2/smock_0.0.2_linux_x86_64.tar.gz"
      sha256 "f946f4d068c7914e43e99969e95158d986e37ad1f7c7017a7026fef7f88ee51e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fcjr/smock/releases/download/v0.0.2/smock_0.0.2_linux_arm64.tar.gz"
      sha256 "804cff818acd13c3e64802026959c838dc6a973bb7e5cb099451993e9266731b"
    end
  end

  def install
    bin.install "smock"
  end
end
