# This file was generated by GoReleaser. DO NOT EDIT.
cask "restorekit-cli" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "76425dc9252bd2bf5307bbe06d617863d084d86b06132f893a1e84432da9fd81"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8bd98ba822315d6a7c4f7252faa0376f4a5f02dc8dbad3f4f089cba0648a821"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38ac632a5d68b218a104529ebd8f9a065aee08449a3e5cf05146e04cb525ecab"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0cc0c663ebd6441278c27e0fd609cee3f3086811743ba06dce854fa21711654"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "restorekit-cli"
  desc "DFU-restore Apple Silicon Macs from the command line"
  homepage "https://github.com/fcjr/restorekit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restorekit"
  bash_completion "completions/restorekit.bash"
  fish_completion "completions/restorekit.fish"
  zsh_completion "completions/restorekit.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/restorekit"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    restorekit triggers DFU mode only from an Apple Silicon Mac host, and
    needs root for that step (sudo restorekit dfu). Restores run on macOS
    and Linux.
  EOS
end
