# This file was generated by GoReleaser. DO NOT EDIT.
cask "restorekit-cli" do
  version "0.5.12"

  on_macos do
    on_arm do
      sha256 "cf437018182d79211e11196eb8335f56fdef0d9c43d1a9cc77e3ccfe9407f2e1"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe125131cae812239305e7f9d2102410e9f71548dfe787a2f6c3419fc6531674"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa4a18a2c6aa1926b6e3b6a17588f1a490daa42c5abfb5588f2a3e3104f3817b"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0dd81eb33eca3a9badfd2ee4058996f61dd4ded2f1f3d64f2e2f8117c09e4189"
      url "https://github.com/fcjr/restorekit/releases/download/v#{version}/restorekit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "restorekit-cli"
  desc "DFU-restore Apple Silicon Macs from the command line"
  homepage "https://github.com/fcjr/restorekit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restorekit"
  bash_completion "completions/restorekit.bash"
  fish_completion "completions/restorekit.fish"
  zsh_completion "completions/restorekit.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/restorekit"]
    elsif OS.linux?
      src = "#{staged_path}/udev/51-restorekit.rules"
      dst = "/etc/udev/rules.d/51-restorekit.rules"
      # Skip the sudo prompt when the rule is already current (upgrades).
      if File.exist?(src) && !(File.exist?(dst) && File.read(dst) == File.read(src))
        ohai "Installing #{dst} so restorekit can reach USB devices without sudo"
        result = begin
          system_command "/bin/sh",
                         args: ["-c", "install -m 0644 '#{src}' '#{dst}' && " \
                                      "udevadm control --reload-rules && udevadm trigger"],
                         sudo: true,
                         must_succeed: false
        rescue StandardError => e
          opoo "sudo failed: #{e.message}"
          nil
        end
        if result&.success?
          ohai "Replug the device for the new permissions to take effect"
        else
          opoo "#{dst} was not installed; restorekit needs sudo until it is (see caveats)"
        end
      end
    end
  end

  zap delete: [
      "/etc/udev/rules.d/51-restorekit.rules",
    ]

  caveats <<~EOS
    restorekit triggers DFU mode only from an Apple Silicon Mac host, and
    needs root for that step (sudo restorekit dfu). Restores run on macOS
    and Linux.

    On Linux this cask installs /etc/udev/rules.d/51-restorekit.rules (asking
    for sudo) so USB access works without root; replug the device afterwards.
    If you skipped that prompt, run `brew reinstall restorekit-cli`, or copy
    udev/51-restorekit.rules out of the Caskroom yourself and run
    `sudo udevadm control --reload-rules && sudo udevadm trigger`.
  EOS
end
